package pl.volleylove.antenka.enums;

public enum RegisterInfo {
    OK, MISSING_INFO, INCORRECT_EMAIL, EMAIL_ALREADY_EXISTS, PASSWORD_DOES_NOT_MEET_REQ,
    INCORRECT_FIRST_NAME, INCORRECT_LAST_NAME, NOT_ALLOWED_AGE
}
