package pl.volleylove.antenka.enums;

public enum SignUpInfo {

    OK, YOU_DO_NOT_MEET_EVENT_REQ, YOU_ARE_NOT_LOGGED_IN,
    SLOT_HAS_PLAYER_ALREADY, EVENT_HAS_NO_FREE_SLOTS_LEFT, YOU_ARE_SINGED_UP_FOR_THIS_EVENT, INCORRECT_EVENT_ID, COMPLETE_PLAYER_OR_TEAM_PROFILE, INCORRECT_SLOT_NUM, EVENT_IS_CLOSED
}
